[platformio]
verbose = true

[env:esp8266_d1_mini_pro_ntp_time_multiband]
platform = espressif8266
board = d1_mini_pro
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
monitor_eol = CRLF
build_flags =
    ; ---- flags indicated transmitter hardware used ----
    -D TX_HARDWARE_USE_SI5351
    ; -D TX_HARDWARE_USE_DUMMY
    ; ---- flags indicated time source used ----
    -D TIME_USE_ESP_WIFI
    ; -D TIME_USE_DUMMY
    ; ---- flags indicating debug levels ----
    -D DEBUG_TX_HARDWARE_USE_DUMMY
    -D DEBUG_TX_HARDWARE_USE_SI5351
    -D DEBUG_NTP_TIME_OBTAINING
    -D DEBUG_FILTER_HARDWARE

